FROM alpine

RUN apk add --no-cache openssh nano curl sudo 

RUN ssh-keygen -A && \
    sed 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' -i /etc/ssh/sshd_config && \
    usermod --shell /bin/bash root && \
    rm -rf /var/cache/apk/*
    
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config"]
