FROM golang:alpine as builder

RUN apk update && apk add --no-cache git \
    && git clone -b master https://github.com/hafkensite/mikrotik-exporter.git  /mikrotik-exporter
    
WORKDIR  /mikrotik-exporter

RUN go build \
    && mv ./mikrotik-exporter /mikrotik-exporter

FROM alpine:latest 

ENV TZ Asia/Shanghai

COPY --from=builder /mikrotik-exporter/mikrotik-exporter /usr/bin/

RUN set -e \
    && apk upgrade \
    && apk add bash tzdata \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && rm -rf /var/cache/apk/*

EXPOSE 9436
 
CMD ["mikrotik-exporter"]
