FROM golang:alpine as builder

RUN apt-get update \
    && apt-get install git \
    && git clone -b master https://github.com/hafkensite/mikrotik-exporter.git  
    
WORKDIR  /mikrotik-exporter

RUN go build \
    && mv ./mikrotik-exporter /mikrotik-exporter

FROM alpine:latest 

ENV TZ Asia/Shanghai

COPY --from=builder /mikrotik-exporter/mikrotik-exporter /usr/bin/

RUN set -e \
    && apk upgrade \
    && apk add bash tzdata \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && rm -rf /var/cache/apk/*

EXPOSE 9436
 
ENTRYPOINT ["mikrotik-exporter", "-config-file", "config.yml"]
